server:
  port: 9191

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    # Set the application name in postgresql, so that it should reflect on pg_stat_activity --> application_name column.
    # https://jdbc.postgresql.org/documentation/91/connect.html#connection-parameters
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:shopease_db}
    username: ${DB_USER_NAME:postgres}
    password: ${DB_PASSWORD:root}

  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:shopease_db}
    user: postgres
    password: root